resources:
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      name: langfuse
      namespace: edmanager
    spec:
      encryptedData:
        asdf: AgC5fSegG9ZAjF6SAY+YUuHxKjmGENsURk/7aBakfB7FV4E7ad5ytza02R33vX+2Y3nSJQ7dULQwmm5PaQTDWZdepuGjy+x0VvmUk1zMv3597VTldXbuuv0O94pfwN6lx92uCHuG6kzO3QUE693fyBGIZU3Xf5k+wXuXT2Lh2Pq6HG8LrZHQJbxgdBdNvvjqSxXw061RaPGqQjsqLpatUEa8OCqpXRSL6A9o6CJVETq2e7Yw2uBEWH1FclzE6Ph2Unuc8qIyGzDUlSZJ3Jp+lQ+9erpwykLvpTmkfMXVly1ilZwvI/9rcjoU2hcLSyqMRVDqbSeNKUwDbESem5UO7vEfOZY2fcFzgEgC71/Ra92VndBAUy0ORZdVknegDQZ/P9V2W1lUqSpW/gZmwlB/sIjFu/f62BOvVEpgb9r0m/ASKvv0r0cOKarsZvwVvErXNMfUu18vhVFied33EPAlTB8AavsCGkCYsg70qvNOCyZ9wFJ3KJah4PgwVwpz+FuTXgIWkh8sGIPaXOuNCcjEini8GjWX8+WyI8fwisdQkNt6HTS233adjcqFcX6CKPOZjJIn2Xi3r1SCL1U+h4pjFwbi2RZdnQ5rm6/cs4E/1Ga9MzDVeIaNYE9Gi1SffdKhMF6MVZ592vHyE5DKzuXr7LnwJdzMlBpqUwiN7zKM8vPmcWJPpv0CXgIoO2MHVOwPNl56fKLtB5dq1COZwd5BYk9tApww9A==
      template:
        metadata:
          name: langfuse
          namespace: edmanager
          annotations:
            argocd.argoproj.io/hook: PreSync
            argocd.argoproj.io/sync-wave: "-10"