---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    asdf: AgAHMPJZpjkglCdvOaqlnz/hOMgRfC1nEmuMb02/KccN+/5EJUkPr9jPwbazMD1YyYkPqhVLztmlZsNKJCgUVapvdVnl731d+By804BlALvXfzmKbf0jAT5noF5fv7sPX4mByqijE+IzrlgRtoFltOCVdzn3RPEL4kGotUQzm/bE8delSem0/8v/AuH0CQP1l7z4R8MUp9fNkoUS487UPGDq5/vfFj3D1rBbfztvpBy+vhXHTSP+3/mT+2kZBGcmGYVUx++vOBnbnaWjahG+DVy4KiVqJokJyUj5JLNIndZ5c2jrxvR5C6tOqnvh5iSFyd1GGD0gVOoloG8i7kA8IblYTkQXfKhgNcZwCjVqjtdO360DXNqYDo0cFWeQ48vox4Z3iHpJWHjlOjXRTgcz4XNdM8V3AtEAcOHeJjzMlhTdUd2DKFBKkzpK/WWljhzi0FBqsPNnlyhhlfPU+mbmnQl5F+c4WVQg/WUIQvg+aq/5e6ZE2jvQbXX+Y9HbG4PI1hu7+e4/C5ygAb1/DJEsoAlk4q7LyY+o6dM+Erybu9D3bBUI2KZH98sMSDOCKm6intTnNPRdvOOKeTsEy/6Sr1yosUCcm6BsNXApN5qHv6vsbXoh+lZEX5Ofg8v/2icms5mfqwnBGWcaeHrOv+WNRoXW2VA5rkLmPRUKCr+yvhSVM4FXfBuTWih4Icf5rMVu/NzD7WkVuCxwdbiXZbPOaoSY3SqTVA==
  template:
    metadata:
      name: langfuse
      namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: upgrade-sql-schema
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: alpine:latest
          command: ["sleep", "5"]
          env:
            - name: LANGFUSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: langfuse
                  key: asdf 
      restartPolicy: Never
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: main
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: maint-page-up
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: page-up
          image: alpine:latest
          command: ["sleep", "2"]
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: main
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: batch/v1
kind: Job
metadata:
  name: maint-page-down
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
        - name: page-down
          image: alpine:latest
          command: ["sleep", "2"]
      restartPolicy: Never
