apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edmanager-platform
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: edmanager
  sources:
    - path: ergo/manifests/charts/application
      repoURL: https://github.com/patrycju/test.git
      targetRevision: master
      helm:
        releaseName: someapp
        valueFiles:
          - $rancher-manifests/ergo/manifests/someapp/configs.yaml
    - path: ergo/manifests/charts/job
      repoURL: https://github.com/patrycju/test.git
      targetRevision: master
      helm:
        releaseName: db-migrations
        valueFiles:
          - $rancher-manifests/ergo/manifests/db-migs/configs.yaml
    - chart: raw
      repoURL: 'https://bedag.github.io/helm-charts/'
      targetRevision: 2.0.0
      helm:
        releaseName: secrets
        valueFiles:
          - $rancher-manifests/ergo/manifests/secrets/configs.yaml
    - repoURL: https://github.com/patrycju/test.git
      targetRevision: master
      ref: rancher-manifests
  destination:
    namespace: edmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
